language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
before_script:
  - mysql -e 'create database enju_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
notifications:
  slack:
    secure: nd4Wr2vUDgELs8xgMoh6KHazQplxuidbxRpFjw7zTAVc9m2rVTqhXq+zH1af8dhUZaImkD8qPu2IfeE0bLxEcF9UZluY9MOQmSx+7Oe9hURgh0HRoYk+XT1915OaR9R7bO7Vs3vHC1W/mWH0dRDF2hv06MSdh+xMz/taB9Js5lM=
sudo: false
dist: precise
